DataLogging:
  Database:
    LoggingDB:
      Path: 'default'
      Rate: 60

Sensors:
  Temperature:
    AirTemperature:
      DeviceID: '28-0218405652ff'
      RecordingID: 'Air_Temperature'
      Mock: 'True'

    WaterTemperature:
      DeviceID: '28-0218405755ff'
      RecordingID: 'Water_Temperature'
      Mock: 'True'
